// src/solid/components/Inner.jsx
import { increment, decrement } from '$redux/features/counter'
import { useStoreContext } from '../context'
import Screen from './Screen'

export default function Inner({}) {
  let [state, fns] = useStoreContext((s) => ({
    value: s.counter.value,
  }), (d) => ({
    decr: () => d(decrement()),
    incr: () => d(increment()),
  }))

  return (
    <div>
      Solid working x: {() => state().value}
      <button onclick={fns.incr}>Incr</button>
      <button onclick={fns.decr}>Decr</button>
      <simple-greeting></simple-greeting>
      <Screen></Screen>
    </div>
  );
}

// src/svelte/components/Inner.svelte
<script>
	import { increment, decrement } from '$redux/features/counter'
	import { useStoreContext } from '../context.svelte.js';
	import Screen from './Screen.svelte';

	let [state, {incr, decr}] = useStoreContext((s) => ({
		value: s.counter.value,
	}), (d) => ({
      decr: () => d(decrement()),
      incr: () => d(increment()),
    }))

</script>
<div>
Svelte working {state.value}
<button onclick={incr}>Incr</button>
<button onclick={decr}>Decr</button>
<simple-greeting></simple-greeting>
<Screen></Screen>
</div>
